# readmitrx/config/feature_config.yaml

features:
  num__:
    - age
    - risk_condition_count
    - sdoh_alcohol_risk
    - sdoh_substance_risk
    - sdoh_emotional_support_score
    - days_until_event
    - total_contact_attempts
    - time_spent_minutes
    - tme_spent_total
    - employment_status_code
    - total_flags
  cat__:
    - None  # Add categorical codes here if available later
  bin__:
    - sex_female
    - race_black
    - race_hispanic
    - race_other
    - language_non_english
    - has_comorbidity
    - hypertension
    - diabetes
    - asthma
    - is_new_patient
    - spoke_to_subject
    - engaged
    - referral_type_ed
    - referral_type_high_risk
    - referral_type_other
    - insurance_na
    - insurance_public
    - insurance_uninsured
    - has_pcp_flag
    - has_insurance_flag
    - housing_insecure_flag
    - housing_insecure_secondary
    - fod_insecure_flag
    - utility_insecure_flag
    - transportation_barrier_flag
    - domestic_violence_risk
    - hiv_test_interest
    - covid_vaccine_signup
    - health_education_needed
    - sdoh_responded
    - has_unmet_needs
    - referrals_made
    - readmit_within_30
    - is_high_risk
  text__:
    - None  # Add free-text fields if introduced later
