# readmitrx/config/feature_config.yaml

features:
  num__:
    - age
    - visit_month
    - chronic_count
    - time_spent_minutes
    - time_spent_total
    - sdoh_alcohol_risk
    - sdoh_substance_risk
    - sdoh_emotional_support_score

  cat__: []
    

  bin__:
    - sex
    - race_black
    - race_hispanic
    - race_other
    - language_non_english
    - has_comorbidity
    - hypertension
    - diabetes
    - asthma
    - is_new_patient
    - spoke_to_subject
    - engaged
    - referral_type_ed
    - referral_type_high_risk
    - referral_type_other
    - insurance_na
    - insurance_public
    - insurance_uninsured
    - has_pcp_flag
    - has_insurance_flag
    - housing_insecure_flag
    # - housing_insecure_secondary
    - food_insecure_flag
    - utility_insecure_flag
    - transportation_insecure_flag
    - domestic_violence_risk
    - hiv_test_interest
    - covid_vaccine_signup
    - health_education_needed
    - sdoh_responded
    - has_unmet_needs
    - referrals_made
    - is_high_risk
    - is_employed_flag

  text__: []
